### ISSUE TITLE
.Net Standard compatibility

### ISSUE THREAD

**Issue by msnelling** [RobThree/TimeZoneMapper#10]
Hi, this is a great library for mapping UNIX timezones to Windows. Would you be able to make a release that supports .Net Standard please?

**Comment by RobThree** [comment]
I would love to but I'm very short on time currently. But a PR is always welcome for review!

**Comment by RobThree** [comment]
I would love to but I'm very short on time currently. But a PR is always welcome for review!

**Comment by ghost1face** [comment]
Looks like .Net Core does not support this natively due to the differences in naming between Unix/Windows.  So this could potentially be a bigger undertaking.  Quickest method would be to implement a mapping between Unix/Windows timezone naming conventions.

[DotNetCore Issue](https://github.com/dotnet/corefx/issues/2538)

**Comment by RobThree** [comment]
> Quickest method would be to implement a mapping between Unix/Windows timezone naming conventions.

@ghost1face  Huh? That's exactly what this package does... I'm not sure we're on the same page? The code for downloading the latest Unicode 'definitions' and such will need to be ported / reimplemented to .Net Core / .Net Standard. But it shouldn't be much work.

**Comment by ghost1face** [comment]
You're right, sorry about that I misread it as he was unable to get this library to work on Unix due to the naming difference for some reason, which in fact seems that he would just like for it to be built for NetStandard/NetCore to potentially use on those systems or mobile platform.

**Comment by ghost1face** [comment]
Noting pull request: #11 has been submitted for this issue.

**Comment by RobThree** [comment]
Noting #11 has been merged and released as [v1.2.20](https://www.nuget.org/packages/TimeZoneMapper/1.2.20)
