### ISSUE TITLE
Missing plattform independency (using a Mac)

### ISSUE THREAD

**Issue by SchneiderSIT** [RobThree/TimeZoneMapper#12]
Your lib is great, thanks for that. However, it does not support the Mac.

I am using the Visual Studio community edition for the Mac. The following code always runs into the catch part with a KeyNotFoundException "The given key was not present in the dictionary".

Please consider to add .NET Core support on the Mac - because it already works on .NET Core (with warnings though...).

    public static T3Z3ValidationResult ValidateTimeZone(string tz) {

            TimeZoneInfo tzi;

            try
            {
                tzi = TimeZoneMap.DefaultValuesTZMapper.MapTZID(tz);

                return new T3Z3ValidationResult() { TimeZoneInfo = tzi, IsValid = true };
            }
            catch
            {
                return new T3Z3ValidationResult() { TimeZoneInfo = null, IsValid = false };
            }
        }

Even when I use a simple timezone like "Europe/Berlin".

**Comment by RobThree** [comment]
Could you debug the problem and:

* Try to see if there's any keys in the dictionary?
* If there's none, could you try to find out why not?
* If there is, could you find out which ones are missing and why?

**Comment by SchneiderSIT** [comment]
The dictionary is empty. Will take a closer look later.

**Comment by RobThree** [comment]
Can you let me know if #11 / [v1.2.20](https://www.nuget.org/packages/TimeZoneMapper/1.2.20) solves your problem?

**Comment by RobThree** [comment]
...assuming it does.
