### ISSUE TITLE
Missing America/Indiana/Indianapolis from default timezone map

### ISSUE THREAD

**Issue by attilabicsko** [RobThree/TimeZoneMapper#13]
Hi! Thank you for the great library, very useful!

I recently noticed that the Timezone ID "America/Indiana/Indianapolis" is missing from the default map xml. I'm aware how to add it with a custom XML or I can change to "America/Indianapolis" which is present in the default map so no huge issue at all, just wanted to let you know.

**Comment by RobThree** [comment]
See #3

**Comment by attilabicsko** [comment]
Makes sense. Should have checked the closed issues first, missed it, sorry. Thanks for the quick answer!

**Comment by RobThree** [comment]
You're welcome. Sorry I cannot be of more help.
