### ISSUE TITLE
Why territory 001 for Europe/Berlin )and not DE?

### ISSUE THREAD

**Issue by dpomt** [RobThree/TimeZoneMapper#14]
Hi, 

great mapping between Windows and IANA time zones, thanks a lot!

Is there any reason why Europe/Berlin has not territory "DE"?

			**<mapZone other="W. Europe Standard Time" territory="001" type="Europe/Berlin"/>**
			<mapZone other="W. Europe Standard Time" territory="AD" type="Europe/Andorra"/>
			<mapZone other="W. Europe Standard Time" territory="AT" type="Europe/Vienna"/>
			<mapZone other="W. Europe Standard Time" territory="CH" type="Europe/Zurich"/>
			<mapZone other="W. Europe Standard Time" territory="DE" type="Europe/Berlin Europe/Busingen"/>

From IANA tz:
DE	+5230+01322	Europe/Berlin	Germany (most areas)

**Comment by RobThree** [comment]
The file is [from unicode.org](https://raw.githubusercontent.com/unicode-org/cldr/master/common/supplemental/windowsZones.xml). But if you look at, for example, London or Paris you'll notice the same.
