### ISSUE TITLE
`TimeZoneMap.DefaultValuesTZMapper` throws exception

### ISSUE THREAD

**Issue by sandrock** [RobThree/TimeZoneMapper#15]
Nuget version: 1.2.31    
OS: Manjaro Linux, Windows 10   
Framework : net462

Calling `TimeZoneMap.DefaultValuesTZMapper` throws the following exception:

```
{System.TimeZoneNotFoundException: The time zone ID 'Yukon Standard Time' was not found on the local computer.
   at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
   at TimeZoneMapper.TZMappers.BaseTZMapper.TryGetTimeZone(String id, Boolean throwOnNonExisting)
   at TimeZoneMapper.TZMappers.BaseTZMapper.<>c__DisplayClass13_0.<.ctor>b__2(XElement n, String t)
   at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at TimeZoneMapper.TZMappers.LinqExtensions.ToDictionarySafe[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer, Boolean throwOnDuplicateKey)
   at TimeZoneMapper.TZMappers.BaseTZMapper..ctor(String xmldata, Boolean throwOnDuplicateKey, Boolean throwOnNonExisting)
   at TimeZoneMapper.TZMappers.DefaultValuesTZMapper..ctor()
   at TimeZoneMapper.TimeZoneMap.<>c.<.cctor>b__9_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at TimeZoneMapper.TimeZoneMap.get_DefaultValuesTZMapper()}
    [System.TimeZoneNotFoundException]: {System.TimeZoneNotFoundException: The time zone ID 'Yukon Standard Time' was not found on the local computer.
   at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
   at TimeZoneMapper.TZMappers.BaseTZMapper.TryGetTimeZone(String id, Boolean throwOnNonExisting)
   at TimeZoneMapper.TZMappers.BaseTZMapper.<>c__DisplayClass13_0.<.ctor>b__2(XElement n, String t)
   at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at TimeZoneMapper.TZMappers.LinqExtensions.ToDictionarySafe[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer, Boolean throwOnDuplicateKey)
   at TimeZoneMapper.TZMappers.BaseTZMapper..ctor(String xmldata, Boolean throwOnDuplicateKey, Boolean throwOnNonExisting)
   at TimeZoneMapper.TZMappers.DefaultValuesTZMapper..ctor()
   at TimeZoneMapper.TimeZoneMap.<>c.<.cctor>b__9_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at TimeZoneMapper.TimeZoneMap.get_DefaultValuesTZMapper()}
    HResult: -2146233088
    InnerException: null
    Message: "The time zone ID 'Yukon Standard Time' was not found on the local computer."
    Source: "mscorlib"
```

This is visible in the [latest appveyor build](https://ci.appveyor.com/project/RobIII/timezonemapper/builds/39067694).

The issue does not occur with nuget version 1.2.30.

**Comment by RobThree** [comment]
You are probably (way) behind on windows updates (august 2020 if I recall correctly). So either update, use an older version or provide a timezonefile to the timezonemapper.

**Comment by sandrock** [comment]
The constructor of `BaseTZMapper` contains a LINQ expression which fails at the following statement:

```
// throwOnNonExisting is true (default value)
(n, t) => new { TZID = t, TZ = TryGetTimeZone(n.Attribute("other").Value, throwOnNonExisting) }
```

It occurs for the "Yukon Standard Time" entry.  It looks related to a [change in windows](https://support.microsoft.com/en-us/topic/dst-changes-in-windows-for-yukon-canada-september-8-2020-ae74d7b8-82ed-1d35-e131-fb0796b73b10) from 2020-09-08. Strangely, I do not have the new "(UTC-07:00) Yukon" tz.

Now with you latest comment:

- updating Windows will not fix the problem for other users of this Windows version
- using an older version of the lib may not be right for users of newer Windows versions
- providing a file... depending on the current windows version? that seems difficult to do.

Would it be possible to have the embed file contain the outdated windows zones?

**Comment by RobThree** [comment]
What would be difficult to do? Just use a CustomTZValuesmapper and pass an XML file in the constructor?
You can also install the update for the timezones separately (don't know the KB number off the cuff, you'll have to google it).

**Comment by sandrock** [comment]
I tried creating a `DefaultValuesTZMapper` specifying `throwOnNonExisting: false` but the constructor is not public :(

**Comment by sandrock** [comment]
> Why would I embed outdated values? The whole point is to stay up to date.

I would like support for older Windows versions.

**Comment by sandrock** [comment]
> What would be difficult to do? Just use a CustomTZValuesmapper and pass an XML file in the constructor? 

That means I have to create a file for each windows revision I want to support. I do not know how to do that.

(thank you for you fast replies on this special day!)

**Comment by sandrock** [comment]
Since `DefaultValuesTZMapper` may throw an exception unpredictably (depending on deployment OS), should we consider changing it for a safer approach? Or document the behavior to consumers?

```
static TimeZoneMap()
{
    _defaultvaluesmapper = new Lazy<DefaultValuesTZMapper>(() => new DefaultValuesTZMapper(throwOnNonExisting: false));
}
```

**Comment by RobThree** [comment]
> > Why would I embed outdated values? The whole point is to stay up to date.
> 
> I would like support for older Windows versions.

You can. All you need is up-to-date Timezone data, which you're gonna need _anyway_.

> That means I have to create a file for each windows revision I want to support. I do not know how to do that.

Why? One file will do? The file is not specific to any windows version?

I'm really not seeing the problem here, I have the feeling we're not on the same page...

**Comment by sandrock** [comment]
Hi,

Here is what I understand this project does.

- unicode maintains a database of time zones
- microsoft also has its database which gets updated by windows update
- this project offers a code that will map a unicode tz into a windows tz
- this project also offers a built-in mapping database so consumers do not have to think about it

Tell me if I'm wrong.

Now, I encounter some issues with the lib and I wish these can be solved and made available through your distribution of the lib. 

1. the DefaultValuesTZMapper property can throw an exception and fail to provide a value
    - I created #16 to allow consumers to prevent the exception 
2. the built-in mapping database is not tolerant to non up-to-date systems
    - I think something can be done about that (maybe with the help of a revision attribute on each mapping, to allow falling back to older windows tz)
    - As I do not exactly know the inner workings and domain, I would like to discuss this. 

You are suggesting me to create my own mapping file. However, I am using this lib in order to not have to worry about that. 

---

Happy new year ^^

**Comment by RobThree** [comment]
> Here is what I understand this project does.
> 
> * unicode maintains a database of time zones

Correct. And "maintains" means there will be updated versions. Which (may) require new(er) mappings. That's why this project is [usually updated](https://www.nuget.org/packages/TimeZoneMapper/) within days, if not hours, when Unicode releases a [new version](https://github.com/RobThree/TimeZoneMapper/commits/master).

> * microsoft also has its database which gets updated by windows update
> * this project offers a code that will map a unicode tz into a windows tz
> * this project also offers a built-in mapping database so consumers do not have to think about it

For all these points I can refer to the above.

> Tell me if I'm wrong.

You're totally correct.

> Now, I encounter some issues with the lib and I wish these can be solved and made available through your distribution of the lib.

You're encountering some issues with the lib _because you're (way) behind on updates_. You can even choose to skip servicepacks or whatever they're called nowadays, you can simply install a single specifically targeted update. You can choose (for whatever reason) to not install these updates, but I assume that people that need to map Yukon would appreciate it if this project keeps up. Maybe you don't need to map it, others may.

> 1. the DefaultValuesTZMapper property can throw an exception and fail to provide a value
>    
>    * I created [Allow custom instance of DefaultValuesTZMapper #16](https://github.com/RobThree/TimeZoneMapper/pull/16) to allow consumers to prevent the exception

Which, don't get me wrong here(!), I appreciate, but I don't think is the / a correct solution to this problem. I think that if you choose not to update using a previous unicode file (which isn't bound to a specific windows version) would be perfectly inline; just [use a unicode file from before august 2020](https://github.com/RobThree/TimeZoneMapper/commits/master/TimeZoneMapper/ResourceFiles/windowsZones.xml). Or modify the current one. And instead of using the `DefaultValuesTZMapper` (which is _just that_, default values), use the `DefaultValuesTZMapper` and point it to your modified file; it will behave in _exactly_ the same way otherwise?

> 2. the built-in mapping database is not tolerant to non up-to-date systems

That's where I disagree. I think it **is**. You just can't use the `DefaultValuesTZMapper`.

>    * I think something can be done about that (maybe with the help of a revision attribute on each mapping, to allow falling back to older windows tz)

We could debate on that, we could consider including a historic version of the Unicode file. But I also think we'd come to the conclusion that that would make things more complicated to use.

>    * As I do not exactly know the inner workings and domain, I would like to discuss this.

I am open to discussion ;-)

> You are suggesting me to create my own mapping file. However, I am using this lib in order to not have to worry about that.

I hope you understand you're not the only one using this library. So while _you_ may not be interested in having the latest data, other users will be.

**Comment by RobThree** [comment]
See #16. I'm considering this resolved.
