### ISSUE TITLE
"America/Indiana/Indianapolis"

### ISSUE THREAD

**Issue by efreeman518** [RobThree/TimeZoneMapper#3]
According to http://en.wikipedia.org/wiki/America/Indiana/Indianapolis, the timezone "America/Indiana/Indianapolis" is in the IANA database, but each call in TimeZoneMapper throws KeyNotFoundException:

TimeZoneMap.OnlineWithFallbackValuesTZMapper.MapTZID(timezone);
TimeZoneMap.DefaultValuesTZMapper.MapTZID(timezone);

What is the recommended way to resolve any timezone in the IANA database to it's Windows Timezone?

**Comment by RobThree** [comment]
Have a look at the [underlying data](http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml). I guess you should use `America/Indianapolis` or create a custom XML and use that.
