### ISSUE TITLE
Please add mapping for "UTC"

### ISSUE THREAD

**Issue by msnelling** [RobThree/TimeZoneMapper#4]
Can you please add a simple mapping for "UTC" instead of having to use "Etc/GMT"?

**Comment by RobThree** [comment]
The mappings come from [CLDR data](http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml) (see [documentation](https://github.com/RobThree/TimeZoneMapper/blob/master/README.md)). You could use a [`CustomValuesTZMapper`](https://github.com/RobThree/TimeZoneMapper/blob/master/TimeZoneMapper/TZMappers/CustomTZMapper.cs) (again, see [documentation](https://github.com/RobThree/TimeZoneMapper/blob/master/README.md)) and modify a CLDR data file to include the desired zone. Or; simply use something like:

    if (someValue == "UTC")
        return TimeZoneMap.DefaultValuesTZMapper.MapTZID("Etc/GMT");
    return TimeZoneMap.DefaultValuesTZMapper.MapTZID(someValue);
