### ISSUE TITLE
KeyNotFoundException

### ISSUE THREAD

**Issue by ghost1face** [RobThree/TimeZoneMapper#6]
Hey,

Don't necessarily want to say this is an issue, you may have designed it this way.  But MapTZID(string tzid) method, was thinking we should use a TryGetValue to safely return a TimeZoneInfo or null object that the user can handle instead of throwing a hard exception.

See here for reference:

https://github.com/RobThree/TimeZoneMapper/blob/master/TimeZoneMapper/TZMappers/BaseTZMapper.cs#L78

What are your thoughts?

**Comment by RobThree** [comment]
> What are your thoughts?

That you're absolutely right :stuck_out_tongue: 
Don't know why I didn't implement that; I usually create a `GetFoo()` and `TryGetFoo()`; this time I somehow seem to have forgotten. Let me fix that...

**Comment by RobThree** [comment]
[1.2.9](https://www.nuget.org/packages/TimeZoneMapper/1.2.9) (commit 5ebcd029cc3f7206eeb114b9a4cd5695fe934deb) :+1:
