### ISSUE TITLE
Issue with GMT-[hours] zones

### ISSUE THREAD

**Issue by minzdrav** [RobThree/TimeZoneMapper#7]
Example:
````c#
    TimeZoneInfo tzi = TimeZoneMap.DefaultValuesTZMapper.MapTZID("Etc/GMT-11");
    Console.WriteLine(tzi.DisplayName);
````
Result:

    (UTC+11:00) Solomon Is., New Caledonia

+11 instead -11.

**Comment by RobThree** [comment]
Can you explain why you think this is correct? This comes directly from the [CLDR data](http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml) from the Unicode consortium.

**Comment by minzdrav** [comment]
Hi @RobThree 
From your url:
<mapZone other="Central Pacific Standard Time" territory="ZZ" type="Etc/GMT-11"/>

From https://msdn.microsoft.com/en-us/library/ms912391(v=winembedded.11).aspx :
"Central Pacific Standard Time" = (GMT+11:00) Magadan, Solomon Islands, New Caledonia

But how -11 can be equal +11?
Here https://www.timeanddate.com/time/map/ -11 = -13. I'm confused now...

**Comment by minzdrav** [comment]
From CLDR data:

```
<!--  (UTC-11:00) Coordinated Universal Time-11  -->
<mapZone other="UTC-11" territory="001" type="Etc/GMT+11"/>
```
Etc/GMT+11 = UTC-11

And
`<mapZone other="Central Pacific Standard Time" territory="ZZ" type="Etc/GMT-11"/>`
Etc/GMT-11 = Central Pacific Standard Time = (GMT+11:00) Magadan, Solomon Islands, New Caledonia

I think something wrong, just not sure where.

**Comment by minzdrav** [comment]
I think nothing to do here. This is standard.
Thank you.
